### ISSUE TITLE
haxe 3.4

### ISSUE THREAD

**Issue by francescoagati** [HaxeFoundation/npm-haxe#11] opened 2016-12-15 15:33 UTC
hi try to install haxe 3.4.0 with rc.1 when i run haxlib from folder node_modules/haxe/bin i get 

```
node_modules/haxe/downloads/haxelib/src/tools/haxelib/Data.hx:66: characters 9-22 : Cannot access non-static field toValidatable from static method

```

**Comment by dmouton** [comment] 2016-12-16 09:04
@clemos can you have a look on it ?

**Comment by clemos** [comment] 2016-12-16 09:14
My diverging version at http://github.com/clemos/npm-haxe doesn't download haxelib separately anymore, as an up-to-date haxelib source is included in the haxe .zip package.
You may want to give it a try, I'll do a PR when confirmed to work better.

**Comment by clemos** [comment] 2016-12-16 09:15
I don't have support for haxe 3.4 yet, though...

**Comment by pypmannetjies** [comment] 2017-01-20 13:19
Having the same problem on 3.4. Also there seems to be a problem with the haxelib_version specified in package.json. Pretty sure it wasn't updated correctly in https://github.com/HaxeFoundation/npm-haxe/commit/c49d680c7b2097b242420b3b183e3ea9ea451549#diff-f16acefe4b6553580c43edab685f50f3

**Comment by jwir3** [comment] 2017-01-30 16:02
@clemos Is there an eta on when support for other versions will come about? I'm trying to use version 3.3.0-rc.1, as this appears to be the only version of haxe for which our app compiles. I'd be happy to submit a PR if you can guide me how to create the package for a specific version...

**Comment by clemos** [comment] 2017-01-30 16:07
I'll have a look at it this week.

**Comment by clemos** [comment] 2017-01-30 16:39
Now you should be (hopefully) able to : 
```bash
npm install --save-dev clemos/npm-haxe#3.3.0-rc.1
#or
npm install --save-dev clemos/npm-haxe#3.4.0-rc.2
```
Let me know how it works, as I've only really tested it on linux64.

**Comment by jwir3** [comment] 2017-01-31 17:09
@clemos Thanks! Works like a charm on MacOS.

**Comment by jwir3** [comment] 2017-02-08 16:51
@clemos Any chance you could publish that version of your package to npmjs.com as `haxe-dev`? The package in the npm repo is a little behind the `master version`, and I have folks that would prefer to use the npm repo package instead of a git link, if possible, in our package.json file.

**Comment by andyli** [comment] 2017-02-09 06:55
@clemos should have commit right to this repo, and he is also a collaborator of the npm haxe package...

**Comment by clemos** [comment] 2017-02-09 08:29
@andyli yeah sorry. 
My branch diverged at some point because the HF branch had been refactored and broke my setup; I had to work something out quickly so I reverted to a previous working version, and continued from there (see https://github.com/HaxeFoundation/npm-haxe/issues/9#issuecomment-247260773).
I'll look into releasing it to npm anyway.

**Comment by cmandlbaur** [comment] 2017-02-13 20:43
Any update on this? I've spent a couple hours trying to track down why a build isn't working only to realise that gulp-haxe is pulling the official version of this lib which was pulling 3.2.1.

**Comment by benmerckx** [comment] 2017-02-13 21:17
@cmandlbaur I'm working on an update for gulp-haxe version which uses [switchx](https://github.com/lix-pm/switchx) instead of this package so a haxe version can be reliably pinned down. I'll try to release later this week.

**Comment by cmandlbaur** [comment] 2017-02-13 21:21
What a legend! Thanks!

**Comment by benmerckx** [comment] 2017-02-17 14:46
@cmandlbaur Released as gulp-haxe 0.3.0 (see: https://github.com/benmerckx/gulp-haxe#set-a-specific-haxe-version)

**Comment by cmandlbaur** [comment] 2017-02-17 15:09
Excellent, thanks for the update!

**Comment by damoebius** [comment] 2017-08-28 13:22
Did you try the latest 4.1.0 version ?
You have a package.json exemple here : https://github.com/HaxeFoundation/npm-haxe/issues/10#issuecomment-325271349

**Closed** 2018-03-21 12:22 UTC
