### ISSUE TITLE
Configuration options don't work?

### ISSUE THREAD

**Issue by dstrekelj** [HaxeFoundation/npm-haxe#10] opened 2016-10-28 16:22 UTC
Hello,

I am trying to use [configuration options ](https://github.com/HaxeFoundation/npm-haxe#configuration-options) in order to install a specific version of Haxe. However, it seems like the options are always ignored in favour of the options provided in npm-haxe's `package.json`.

For reference, here is my project's `package.json` file:

```
{
  "name": "haxe-js",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "haxe build.hxml"
  },
  "author": "dstrekelj <domagojstrekelj@gmail.com>",
  "license": "IDGAF",
  "devDependencies": {
    "haxe": "^4.0.0"
  },
  "config": {
    "haxe:nightly": "2016-10-26_development_bc173ef",
    "haxe:haxelib_version": "3.2.0-rc.1"
  }
}
```

I also tried omitting the `haxe:` prefix from the config options, but without success.

Any help or insight is appreciated!

**Comment by dstrekelj** [comment] 2016-10-28 16:23
Sorry, forgot add I'm using Node v6.4.0 and NPM v3.10.3.

**Comment by clemos** [comment] 2016-10-31 01:45
You're right, it only seems to work from `npm-haxe`'s `package.json` :\

**Comment by dstrekelj** [comment] 2016-10-31 11:29
I'm not that well versed in NPM, so I'm not sure whether this is even an issue at all - this behaviour could be by design. The documentation ([1][1], [2][2]) leads me to believe the configuration should be overwritten, but that clearly isn't happening.

If all else fails, would it be feasible to set up npm-haxe as an installer script which uses a configuration file (e.g. JSON-formatted `.haxerc`) to grab or set the appropriate builds? It would be an extra step in the installation process, requiring an NPM script to initialise everything (e.g. `npm run setup`), but it's not uncommon practice among other NPM packages The configuration file would be placed in the project root, or passed to the npm-haxe script explicitly. The script would parse the data and fetch requested Haxe builds.

I'm only theorising, of course. I would really like for this to pan out because it would be a great way to push for Haxe at workplaces where the NPM 'way of life' is deeply ingrained in developers.

[1]: https://docs.npmjs.com/misc/config#per-package-config-settings
[2]: https://docs.npmjs.com/misc/scripts#configuration

**Comment by clemos** [comment] 2016-10-31 13:14
I'll make more tests, because I'm pretty sure it was somehow working at some point.
In anycase, what you can do meanwhile is fork the repo, change the config and install the package via `npm install dstrekelj/npm-haxe`, which I think is not bad, all in all :p

**Comment by lucas-jones** [comment] 2017-06-26 18:49
Any chance on a fix?

**Comment by clemos** [comment] 2017-06-27 09:27
I think we should just remove this "feature", as it seems NPM is not designed for this kind of usage...

**Comment by damoebius** [comment] 2017-08-28 06:33
It works for me
`"dependencies": {
    "haxe": "4.1.0",
    "taminahx": "1.2.0",
    "mconsole-npm": ">=1.6.1",
    "msignal": ">=1.2.3",
    "nodehx": ">=0.0.13",
    "sakurahx-api": ">=5.2.x",
    "exifhx": ">=0.0.1",
    "createjs-haxe": ">1.6.7"
  },
  "config": {
    "haxe": "3.4.2",
    "haxelib_version": "3.2.0-rc.1"
}`

**Comment by clemos** [comment] 2017-08-28 08:06
@damoebius you're right, it seems to work with current 4.1.0 package, which is good :D 
my repo seems to have a regression, though, because it doesn't work with `"haxe":"clemos/npm-haxe"` :S

**Comment by clemos** [comment] 2017-08-28 08:20
Ok so this [commit](https://github.com/HaxeFoundation/npm-haxe/commit/c49d680c7b2097b242420b3b183e3ea9ea451549) makes the `haxe` and `haxelib_version` config entries to work (but not `nightly`)
I don't have it in my repo, and I don't really want to depend on packages like `parent-package-json`, so config fields won't work for now

**Comment by clemos** [comment] 2017-08-28 09:23
FYI, you can override package.json's `config` entries using a local `.npmrc` file instead, see https://docs.npmjs.com/files/npmrc
I think it's a good way to go, even though this probably won't work with dependencies (but it's probably okay?).

**Comment by damoebius** [comment] 2017-08-28 13:19
OK, i'll have a look on .npmrc usage, i don't like parent-package-json too but it works like this.
Can we close this issue and create a new one as an improvement if .npmrc is a good way ?

**Comment by damoebius** [comment] 2018-04-03 12:32
Have a look on : https://github.com/HaxeFoundation/npm-haxe/tree/feature/haxelib_dependencies

**Closed by damoebius** 2018-04-03 12:32 UTC
